# NeuralQuest Configuration for Pokemon Red
# Optimized for RPG exploration and long-horizon gameplay
# Maintains domain-agnostic principles

[env]
frame_skip = 4          # Standard frame skip for RPG pacing
sticky_p = 0.05         # Lower sticky probability for precise menu navigation
seed = 1337             # Reproducible seed
max_episode_steps = 1500   # Shorter episodes to enable frontier sampling
deterministic = true    # Enable deterministic execution

[algo]
gamma = 0.999           # Higher discount for long-term planning in RPGs
gae_lambda = 0.97       # Higher GAE lambda for temporal credit assignment
lr_policy = 2e-4        # Slightly lower learning rate for stability
lr_value = 2e-4         # Matched value learning rate
batch_horizon = 1500    # Match episode length for proper episode completion
entropy_coeff = 0.02    # Higher entropy for exploration variety
value_coeff = 0.5       # Standard value coefficient
grad_clip = 10.0        # Higher gradient clip for stability
epochs_per_update = 4   # Multiple epochs per update
minibatch_size = 512    # Larger minibatches

[rnd]
beta = 0.15             # Lower intrinsic reward scaling (RPGs have natural progression)
lr = 8e-4               # Slightly lower RND learning rate
reward_clip = 10.0      # Higher reward clip for diverse experiences
norm_ema = 0.995        # Slower normalization for stable long-term training
hidden_dim = 256        # Larger RND networks for complex state space

[archive]
hash_bits = 64          # Full 64-bit hashing for large state space
capacity = 100000       # Much larger archive for RPG world exploration
p_frontier = 0.8        # Higher frontier probability to escape menu loops
novel_lru = 10000       # Larger LRU window for RPG state persistence
evict_on = "old_and_often"  # Eviction strategy
hamming_threshold = 3   # Higher threshold for meaningful state differences
projection_dim = 128    # Larger projection for rich state representation

[train]
epochs = 50000          # Very long training for RPG mastery
ckpt_every = 500        # More frequent checkpoints for long training
log_every = 50          # Less frequent logging
eval_every = 2500       # Periodic evaluation
save_dir = "pokemon_checkpoints"  # Pokemon-specific checkpoint directory
log_dir = "pokemon_logs"          # Pokemon-specific log directory