# NeuralQuest Smoke Test Configuration
# Fast configuration for testing and debugging

[env]
frame_skip = 4
sticky_p = 0.1
seed = 1337
max_episode_steps = 1000    # Shorter episodes for testing
deterministic = true

[algo]
gamma = 0.99                # Slightly faster discounting
gae_lambda = 0.95
lr_policy = 1e-3            # Higher learning rate for faster learning
lr_value = 1e-3
batch_horizon = 128         # Smaller batch for faster updates
entropy_coeff = 0.02        # Higher entropy for more exploration
value_coeff = 0.5
grad_clip = 5.0
epochs_per_update = 2       # Fewer epochs per update
minibatch_size = 64         # Smaller minibatches
hidden_dim = 128            # Smaller networks for speed

[rnd]
beta = 0.3                  # Higher intrinsic reward scaling
lr = 5e-3                   # Higher RND learning rate
reward_clip = 3.0
norm_ema = 0.95
hidden_dim = 64             # Smaller networks for speed

[archive]
hash_bits = 32              # Fewer hash bits for testing
capacity = 1000             # Smaller archive capacity
p_frontier = 0.5            # More frequent frontier resets
novel_lru = 500             # Smaller LRU window
evict_on = "old_and_often"
hamming_threshold = 1       # Lower threshold for novelty
projection_dim = 32         # Smaller projection dimension

[train]
epochs = 50                 # Very few epochs for smoke test
ckpt_every = 10             # Frequent checkpoints
log_every = 1               # Log every epoch
eval_every = 25             # Infrequent evaluation
save_dir = "test_checkpoints"
log_dir = "test_logs"